//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOS_VS_CONFIGURACION_PEDIDO
    {
        public int id_vs { get; set; }
        public int id_configuracion { get; set; }
        public int id_articulo { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
        public virtual CONFIGURACION_PEDIDOS CONFIGURACION_PEDIDOS { get; set; }
    }
}
