//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIAS_SERVICIOS
    {
        public int id_categoria_servicio { get; set; }
        public string categoria { get; set; }
        public string descripcion { get; set; }
        public bool estado { get; set; }
    }
}
