//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBROS
    {
        public int id_cobro { get; set; }
        public int id_financiamiento { get; set; }
        public int id_empleado { get; set; }
        public string usuario { get; set; }
        public int num_cuota { get; set; }
        public System.DateTime fecha { get; set; }
        public double monto { get; set; }
        public double mora { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual FINANCIAMIENTOS FINANCIAMIENTOS { get; set; }
    }
}
