//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUOTAS
    {
        public int id_cuotas { get; set; }
        public int id_financiamiento { get; set; }
        public int num_cuota { get; set; }
        public double tasa { get; set; }
        public double monto { get; set; }
        public bool estado { get; set; }
    
        public virtual FINANCIAMIENTOS FINANCIAMIENTOS { get; set; }
    }
}
