//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLES_PEDIDOS
    {
        public int num_pedido { get; set; }
        public int id_articulo { get; set; }
        public double cantidad { get; set; }
        public double precio { get; set; }
        public int ID { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
        public virtual PEDIDOS PEDIDOS { get; set; }
    }
}
