//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVIAJES
    {
        public int id_dviaje { get; set; }
        public int id_viaje { get; set; }
        public System.DateTime fecha_recogidaA { get; set; }
        public System.DateTime fecha_recogidaB { get; set; }
        public string direc_recogida { get; set; }
        public Nullable<bool> escaleras { get; set; }
        public string num_habitacion_recogida { get; set; }
        public string instrucciones_recodida { get; set; }
        public string contacto_recogida { get; set; }
        public string direc_destino { get; set; }
        public string num_habitacion_destino { get; set; }
        public string instrucciones_destino { get; set; }
        public string contacto_destino { get; set; }
    }
}
