//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCIAMIENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FINANCIAMIENTOS()
        {
            this.COBROS = new HashSet<COBROS>();
            this.CUOTAS = new HashSet<CUOTAS>();
        }
    
        public int id_financiamiento { get; set; }
        public int id_articulo { get; set; }
        public int id_cliente { get; set; }
        public int id_empleado { get; set; }
        public int cant_cuota { get; set; }
        public double tasa { get; set; }
        public System.DateTime fecha { get; set; }
        public string duracion { get; set; }
        public double monto { get; set; }
        public bool estado { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COBROS> COBROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUOTAS> CUOTAS { get; set; }
        public virtual EMPLEADOS EMPLEADOS { get; set; }
    }
}
