//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPS
    {
        public int id_vehiculo { get; set; }
        public int id_empleado { get; set; }
        public System.Data.Entity.Spatial.DbGeography latitud { get; set; }
        public System.Data.Entity.Spatial.DbGeography longitud { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
    }
}
