//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCF
    {
        public int intNCF { get; set; }
        public string serie { get; set; }
        public Nullable<int> numTipo { get; set; }
        public Nullable<int> secuencia { get; set; }
        public Nullable<int> reorden { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
