//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTES()
        {
            this.VIAJES = new HashSet<VIAJES>();
        }
    
        public int id_paciente { get; set; }
        public int id_persona { get; set; }
        public double peso { get; set; }
        public string num_seguro { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string alergias { get; set; }
        public bool epilectico { get; set; }
        public string historial_medico { get; set; }
        public string medicamentos { get; set; }
        public bool estado { get; set; }
    
        public virtual PERSONAS PERSONAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIAJES> VIAJES { get; set; }
    }
}
