//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDOS()
        {
            this.DETALLES_PEDIDOS = new HashSet<DETALLES_PEDIDOS>();
        }
    
        public int num_pedido { get; set; }
        public int id_suplidor { get; set; }
        public double total { get; set; }
        public int estado { get; set; }
        public System.DateTime creado { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES_PEDIDOS> DETALLES_PEDIDOS { get; set; }
        public virtual SUPLIDORES SUPLIDORES { get; set; }
    }
}
