//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONAS()
        {
            this.EMPLEADOS = new HashSet<EMPLEADOS>();
        }
    
        public int id_persona { get; set; }
        public int id_tercero { get; set; }
        public int id_sexo { get; set; }
        public int id_nacionalidad { get; set; }
        public string apellido { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual NACIONALIDADES NACIONALIDADES { get; set; }
        public virtual SEXOS SEXOS { get; set; }
        public virtual TERCEROS TERCEROS { get; set; }
    }
}
