//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TELEFONOS()
        {
            this.TERCEROS_VS_TELEFONOS = new HashSet<TERCEROS_VS_TELEFONOS>();
        }
    
        public int id_telefono { get; set; }
        public int id_tipo_telefono { get; set; }
        public string telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TERCEROS_VS_TELEFONOS> TERCEROS_VS_TELEFONOS { get; set; }
        public virtual TIPOS_TELEFONOS TIPOS_TELEFONOS { get; set; }
    }
}
