//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOSVIAJES
    {
        public int id_tipoViaje { get; set; }
        public string descripcionViaje { get; set; }
        public double precio { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
