//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE
    {
        public int id_transporte { get; set; }
        public Nullable<int> id_conductor { get; set; }
        public string num_fact { get; set; }
        public System.DateTime fecha { get; set; }
        public string notas_viaje { get; set; }
        public Nullable<int> id_dir_desde { get; set; }
        public Nullable<int> id_dir_hasta { get; set; }
        public int estado { get; set; }
        public int id_vehiculo { get; set; }
    
        public virtual CONDUCTOR CONDUCTOR { get; set; }
    }
}
