//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE
    {
        public int intTransporte { get; set; }
        public int numFactura { get; set; }
        public int intEmpleado { get; set; }
        public int intVehiculo { get; set; }
        public int intDireccion { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    }
}
