//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int id_usuario { get; set; }
        public string usuario { get; set; }
        public int id_empleado { get; set; }
        public int id_tipo_usuario { get; set; }
        public string contrasena { get; set; }
        public bool estado { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual TIPOS_USUARIOS TIPOS_USUARIOS { get; set; }
    }
}
