//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _911_RD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAJES
    {
        public int id_viaje { get; set; }
        public int id_tipoPago { get; set; }
        public int id_cliente { get; set; }
        public int id_paciente { get; set; }
        public int id_tipoViaje { get; set; }
        public Nullable<int> id_conductor { get; set; }
        public bool oxigeno { get; set; }
        public bool silla_rueda { get; set; }
        public bool camilla { get; set; }
        public int acompanante { get; set; }
        public int personal_ayudante { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_recogida { get; set; }
        public string direc_recogida { get; set; }
        public string num_habitacion_recogida { get; set; }
        public string instrucciones_recodida { get; set; }
        public string contacto_recodigda { get; set; }
        public string direc_destino { get; set; }
        public string num_habitacion_destino { get; set; }
        public string instrucciones_destino { get; set; }
        public string contacto_destino { get; set; }
        public string notas_viaje { get; set; }
        public double total_viaje { get; set; }
        public double subtotal_viaje { get; set; }
        public double descuento { get; set; }
        public double itbis { get; set; }
        public int estado { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual CONDUCTOR CONDUCTOR { get; set; }
        public virtual PACIENTES PACIENTES { get; set; }
        public virtual TIPOSPAGO TIPOSPAGO { get; set; }
        public virtual TIPOSVIAJES TIPOSVIAJES { get; set; }
    }
}
